---
abstract: 'Parse and format CLDR time patterns'
author:
  - 'Maroš Kollár'
build_requires:
  Test::Exception: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Format-CLDR
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0.4304
  DateTime::Locale: 0.41
  DateTime::TimeZone: 0
  Params::Validate: 0
  perl: 5.8.0
version: 1.01
