---
abstract: 'Parse and format CLDR time patterns'
author:
  - 'Maroš Kollár'
build_requires:
  Exporter: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-CLDR
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0.44
  DateTime::Incomplete: 0
  DateTime::Locale: 0.42
  DateTime::TimeZone: 0
  Params::Validate: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.06
